# This config file is for use with the `build_data` and `check_data` functions,
# which are helpers for implementations of Open SDG. This file allows easy use
# of those functions without altering Python code.

# Languages
# ---------
# This tells sdg-build to perform "translated builds" for each of the specified
# languages. Each build is in its own subfolder - one for each language.
languages:
  - en
  - fr

# Destination directory
# ---------------------
# This identifies a directory to hold the "built" files. The default is '_site'.
site_dir: _site

# Schema file
# -----------
# This identifies a file containing the schema (possible fields) for metadata.
# Currently this needs to be a prose.io config, and defaults to '_prose.yml'.
schema_file: metadata_schema.yml

# Source directory
# ----------------
# This identifies the directory that holds the 'data' and 'meta' folders.
# The default, '', points to the root of this repository.
src_dir: ''

# Inputs
# ------
# The allows control over the inputs of data and metadata. This can be omitted
# if you are using the standard Open SDG approach of CSV data and YAML metadata.
# But if you would like to use non-standard inputs (such as SDMX) then you can
# use this as needed.
#
# Each item must have a "class" which corresponds to classes in the sdg/inputs
# folder. Further, each item can have any/all of the parameters that class uses.
# The defaults below show what is used when this is omitted.
inputs:
  #- class: InputSdmxMl_Multiple
  #  path_pattern: 'data/*.xml'
  #  dsd: 'LocalRegistry.xml'
  - class: InputSdmxMl_Structure
    source: https://sn.sdmx.afdb.org/ns-ws/rest/data/SN1,DF_SDG_NAIROBIWS_ID_TEST_001,1.0/A............../ALL/?detail=full&dimensionAtObservation=TIME_PERIOD
    dsd: https://sn.sdmx.afdb.org/ns-ws/rest/datastructure/SN1/SDG/1.0/?detail=Full&references=Descendants
    dimension_map:
      REF_AREA|SN: ''
    drop_dimensions:
      - FREQ
      - REPORTING_TYPE
      - NATURE
      - TIME_COVERAGE
    drop_singleton_dimensions: false
    import_codes: true
    import_series_attributes: true
    import_observation_attributes: true
    indicator_id_map:
     _L_030801_01: 3-8-1
     _L_SN_0100101_1: 10-1-1
     _L_SN_040601_1: 4-6-1
     _L_SN0140701_1: 14-7-1
     AG_LND_FRSTMGT: 15-1-2
     _L_SN_040101_1: 4-1-1
     _L_SN_040101_2: 4-1-1
     _L_SN_040202_1: 4-2-2
     _L_SN_040301_1: 4-3-1     
     _L_SN_040301_2: 4-3-1
     VC_VAW_MARR: 5-2-1
     VC_VAW_PSYV: 5-2-1
     VC_VAW_PHYV: 5-2-1
     VC_VAW_SEXV: 5-2-1
     _L_SN_020401_1 : 2-4-1
     _L_SN_030301_1 : 3-3-1
     _L_SN_030801_1 : 3-8-1
     _L_SN_050202_1 : 5-2-2
     SP_DYN_MRBF15 : 5-3-1
     SP_DYN_MRBF18 : 5-3-1
     _L_SN_050302_1 : 5-3-2
     _L_SN_050502_2 : 5-5-2
     _L_SN_050502_1 : 5-5-2
     _L_SN_050601_1 : 5-6-1
     _L_SN_050a01_3 : 5-a-1
     _L_SN_050a01_1 : 5-a-1
     _L_SN_050a01_2 : 5-a-1
     _L_SN_050b01_1 : 5-b-1
     IT_MOB_OWN : 5-b-1
     _L_SN_060101_1 : 6-1-1
     _L_SN_060201_1 : 6-2-1
     _L_SN_070201_1 : 7-2-1
     EG_EGY_RNEW : 7-b-1
     _L_SN_080902_2 : 8-9-2
     FB_CBK_BRCH : 8-10-1
     FB_ATM_TOTL : 8-10-1
     _L_SN_0801002_1 : 8-10-2
     _L_SN_0901020a_2 : 9-1-2
     _L_SN_0100501_1 : 10-5-1
     _L_SN_0110101_1 : 11-1-1
     _L_SN_0110302_1 : 11-3-2
     _L_SN_0110401_1 : 11-4-1
     _L_SN_0110602_1 : 11-6-2
     _L_SN_0110602_2 : 11-6-2
     _L_SN_0110701_1 : 11-7-1
     AG_LND_FRSTMGT : 15-2-1
     _L_SN_0160301_1 : 16-3-1
     _L_SN_0160301_2 : 16-3-1
     
    request_params: 
      headers: 
        User-Agent: Open-SDG-Build-1 
  - class: InputYamlMeta
    path_pattern: indicator-config/*-*.yml
    git: false  
  - class: InputWordMeta
    path_pattern: meta/*-*.docm
  - class: InputYamlMeta
    # This describes the meta files, relative to the "src_dir" indicated above.
    path_pattern: meta/*-*.yml
    # This specifies whether or not to use Git to calculate the "last updated"
    # dates for data files.
    git: true
    # This specifies an alternate folder to look in for Git-versioned data files,
    # when calculating the "last updated" dates for data files. This defaults to
    # "data" (the folder where the data files actually exist.) Most sites will not
    # need to change this setting. It is intended for sites where the data needs
    # to be "built" before being processed by sdg-build.
    git_data_dir: data
  - class: InputSdmxMeta
    meta_suffix: __GLOBAL
# Metadata Schema
# This inputs multiple metadata schema to control which metadata tabs
# the various fields appear in (eg, National, Global, Sources)
#  - class: SchemaInputSdmxMsd
#    schema_path: SDG_MSD.xml
#    scope: national
# Translations
# ------------
# The allows control over the imported translations. This can be omitted if you
# are happy with the defaults. But if you are using custom translation repos
# or non-standard inputs (such as SDMX) then you can use this as needed.
#
# Each item must have a "class" which corresponds to classes in the sdg-build
# project. Further, each item can have any/all of the parameters that class uses.
# The defaults below show what is used when this is omitted.
translations:
  # This pulls in translations from a Git repository.
  - class: TranslationInputSdgTranslations
    source: https://github.com/open-sdg/sdg-translations.git
    tag: 2.4.0-beta5
  # This pulls in translations from a local 'translations' folder.
  - class: TranslationInputYaml
    source: translations
  #- class: TranslationInputSdmx
  #  source: 'LocalRegistry.xml'
  - class: TranslationInputSdmx
    source: https://sn.sdmx.afdb.org/ns-ws/rest/datastructure/SN1/SDG/1.0/?detail=Full&references=Descendants
    request_params:
      headers:
        User-Agent: Open-SDG-Build-1

# Reporting status extra fields
# -----------------------------
# This allows the build to generate stats for reporting status by additional
# fields, beyond the default "status by goal" report.
reporting_status_extra_fields: []

# Map layers
# ----------
# This allows the build to generate one or more GeoJSON files to be used by
# Open SDG maps. The parameters available correspond to the OutputGeoJson class.
# See sdg/outputs/OutputGeoJson.py for more information. Uncomment the map_layers
# below and adjust if you would like to use the Open SDG mapping functionality.
# Note that the GeoJSON files can either be remote (as in the example below) or
# local, relative to the src_dir specified above.
#map_layers:
#  - geojson_file: https://geoportal1-ons.opendata.arcgis.com/datasets/4fcca2a47fed4bfaa1793015a18537ac_4.geojson
#    name_property: rgn17nm
#    id_property: rgn17cd
#    output_subfolder: regions
#    filename_prefix: indicator_

# Documentation settings
# ----------------------
# This controls the automatic documentation that is created for your build.
#
# This is the logo at the top of the automated documentation pages.
docs_branding: SDG data build documentation
# This displays at the top of the automated documentation homepage.
docs_intro: This is a list of examples of endpoints and output that are
  available on this service. Click each of the links below for more information
  on the available output.
# This can be uncommented and updated so allow links to your indicator pages.
# The URL here should have [id] instead of the indicator ID.
#docs_indicator_url: https://my-github-org/my-site-repository/[id]
# This can be uncommented to show translation columns in the disaggregation report.
#docs_translate_disaggregations: true
# This can be uncommented to show additional columns in the disaggregation report.
# This is mainly intended to show units of measurement and series, which are not
# normally considered "disaggregation".
# docs_extra_disaggregations: ['Units', 'Series']

# This controls the metadata report which is part of the automatic documentation.
# More info can be found at https://open-sdg.readthedocs.io/en/latest/data-configuration/#docs_metadata_fields
docs_metadata_fields:
    - key: reporting_status
      label: Reporting status
    - key: SDG_CUSTODIAN_AGENCIES__GLOBAL
      label: UN custodian agency
    - key: data_non_statistical
      label: Non-statistical
    - key: data_show_map
      label: Show map
    - key: national_geographical_coverage
      label: Geographical coverage
    - key: computation_units
      label: Units
    - key: graph_type
      label: Graph type

indicator_options:
  non_disaggregation_columns:
    - Year
    - Units
    - Series
    - Value
    - GeoCode
    - Observation status
    - Unit multiplier
    - Unit measure
    - UNIT_MEASURE
    - SERIES
    - COMMENT_TS
    - DATA_LAST_UPDATE
  series_column: SERIES
  unit_column: UNIT_MEASURE
  observation_attributes:
    - COMMENT_OBS
    - SOURCE_DETAIL
